// Auto-generated IANA timezone options from @vvo/tzdb
// Canonical modern names with country names + GMT offsets
// Total: 316 timezones

export const const_TimezoneOptions = [
    { label: "UTC (GMT)", value: "UTC" },
    {
        label: "Pacific/Midway - United States Minor Outlying Islands (GMT-11)",
        value: "Pacific/Midway",
    },
    { label: "Pacific/Pago Pago - American Samoa (GMT-11)", value: "Pacific/Pago_Pago" },
    { label: "Pacific/Niue - Niue (GMT-11)", value: "Pacific/Niue" },
    { label: "Pacific/Rarotonga - Cook Islands (GMT-10)", value: "Pacific/Rarotonga" },
    { label: "Pacific/Honolulu - United States (GMT-10)", value: "Pacific/Honolulu" },
    { label: "Pacific/Tahiti - French Polynesia (GMT-10)", value: "Pacific/Tahiti" },
    { label: "Pacific/Marquesas - French Polynesia (GMT-10:30)", value: "Pacific/Marquesas" },
    { label: "Pacific/Gambier - French Polynesia (GMT-9)", value: "Pacific/Gambier" },
    { label: "America/Adak - United States (GMT-10)", value: "America/Adak" },
    { label: "America/Anchorage - United States (GMT-9)", value: "America/Anchorage" },
    { label: "Pacific/Pitcairn - Pitcairn (GMT-8)", value: "Pacific/Pitcairn" },
    { label: "America/Hermosillo - Mexico (GMT-7)", value: "America/Hermosillo" },
    { label: "America/Phoenix - United States (GMT-7)", value: "America/Phoenix" },
    { label: "America/Los Angeles - United States (GMT-8)", value: "America/Los_Angeles" },
    { label: "America/Tijuana - Mexico (GMT-8)", value: "America/Tijuana" },
    { label: "America/Vancouver - Canada (GMT-8)", value: "America/Vancouver" },
    { label: "America/Whitehorse - Canada (GMT-7)", value: "America/Whitehorse" },
    { label: "America/Belize - Belize (GMT-6)", value: "America/Belize" },
    { label: "America/Guatemala - Guatemala (GMT-6)", value: "America/Guatemala" },
    { label: "America/Managua - Nicaragua (GMT-6)", value: "America/Managua" },
    { label: "America/Mexico City - Mexico (GMT-6)", value: "America/Mexico_City" },
    { label: "America/Costa Rica - Costa Rica (GMT-6)", value: "America/Costa_Rica" },
    { label: "America/El Salvador - El Salvador (GMT-6)", value: "America/El_Salvador" },
    { label: "America/Regina - Canada (GMT-6)", value: "America/Regina" },
    { label: "America/Tegucigalpa - Honduras (GMT-6)", value: "America/Tegucigalpa" },
    { label: "Pacific/Easter - Chile (GMT-6)", value: "Pacific/Easter" },
    { label: "Pacific/Galapagos - Ecuador (GMT-6)", value: "Pacific/Galapagos" },
    { label: "America/Edmonton - Canada (GMT-7)", value: "America/Edmonton" },
    { label: "America/Ciudad Juarez - Mexico (GMT-7)", value: "America/Ciudad_Juarez" },
    { label: "America/Denver - United States (GMT-7)", value: "America/Denver" },
    { label: "America/Rio Branco - Brazil (GMT-5)", value: "America/Rio_Branco" },
    { label: "America/Chicago - United States (GMT-6)", value: "America/Chicago" },
    { label: "America/Matamoros - Mexico (GMT-6)", value: "America/Matamoros" },
    { label: "America/Winnipeg - Canada (GMT-6)", value: "America/Winnipeg" },
    { label: "America/Bogota - Colombia (GMT-5)", value: "America/Bogota" },
    { label: "America/Atikokan - Canada (GMT-5)", value: "America/Atikokan" },
    { label: "America/Cancun - Mexico (GMT-5)", value: "America/Cancun" },
    { label: "America/Cayman - Cayman Islands (GMT-5)", value: "America/Cayman" },
    { label: "America/Jamaica - Jamaica (GMT-5)", value: "America/Jamaica" },
    { label: "America/Panama - Panama (GMT-5)", value: "America/Panama" },
    { label: "America/Guayaquil - Ecuador (GMT-5)", value: "America/Guayaquil" },
    { label: "America/Lima - Peru (GMT-5)", value: "America/Lima" },
    { label: "America/Manaus - Brazil (GMT-4)", value: "America/Manaus" },
    { label: "America/St Kitts - Saint Kitts and Nevis (GMT-4)", value: "America/St_Kitts" },
    { label: "America/Blanc-Sablon - Canada (GMT-4)", value: "America/Blanc-Sablon" },
    { label: "America/Montserrat - Montserrat (GMT-4)", value: "America/Montserrat" },
    { label: "America/Barbados - Barbados (GMT-4)", value: "America/Barbados" },
    {
        label: "America/Port of Spain - Trinidad and Tobago (GMT-4)",
        value: "America/Port_of_Spain",
    },
    { label: "America/Martinique - Martinique (GMT-4)", value: "America/Martinique" },
    { label: "America/St Lucia - Saint Lucia (GMT-4)", value: "America/St_Lucia" },
    { label: "America/St Barthelemy - Saint Barthelemy (GMT-4)", value: "America/St_Barthelemy" },
    {
        label: "America/St Vincent - Saint Vincent and the Grenadines (GMT-4)",
        value: "America/St_Vincent",
    },
    {
        label: "America/Kralendijk - Bonaire, Saint Eustatius and Saba  (GMT-4)",
        value: "America/Kralendijk",
    },
    { label: "America/Guadeloupe - Guadeloupe (GMT-4)", value: "America/Guadeloupe" },
    { label: "America/Marigot - Saint Martin (GMT-4)", value: "America/Marigot" },
    { label: "America/Aruba - Aruba (GMT-4)", value: "America/Aruba" },
    { label: "America/Lower Princes - Sint Maarten (GMT-4)", value: "America/Lower_Princes" },
    { label: "America/Tortola - British Virgin Islands (GMT-4)", value: "America/Tortola" },
    { label: "America/Dominica - Dominica (GMT-4)", value: "America/Dominica" },
    { label: "America/St Thomas - U.S. Virgin Islands (GMT-4)", value: "America/St_Thomas" },
    { label: "America/Grenada - Grenada (GMT-4)", value: "America/Grenada" },
    { label: "America/Antigua - Antigua and Barbuda (GMT-4)", value: "America/Antigua" },
    { label: "America/Puerto Rico - Puerto Rico (GMT-4)", value: "America/Puerto_Rico" },
    { label: "America/Santo Domingo - Dominican Republic (GMT-4)", value: "America/Santo_Domingo" },
    { label: "America/Anguilla - Anguilla (GMT-4)", value: "America/Anguilla" },
    { label: "America/Curacao - Curacao (GMT-4)", value: "America/Curacao" },
    { label: "America/La Paz - Bolivia (GMT-4)", value: "America/La_Paz" },
    { label: "America/Santiago - Chile (GMT-4)", value: "America/Santiago" },
    { label: "America/Havana - Cuba (GMT-5)", value: "America/Havana" },
    { label: "America/Nassau - Bahamas (GMT-5)", value: "America/Nassau" },
    { label: "America/New York - United States (GMT-5)", value: "America/New_York" },
    { label: "America/Port-au-Prince - Haiti (GMT-5)", value: "America/Port-au-Prince" },
    { label: "America/Grand Turk - Turks and Caicos Islands (GMT-5)", value: "America/Grand_Turk" },
    { label: "America/Toronto - Canada (GMT-5)", value: "America/Toronto" },
    { label: "America/Guyana - Guyana (GMT-4)", value: "America/Guyana" },
    { label: "America/Caracas - Venezuela (GMT-4)", value: "America/Caracas" },
    {
        label: "America/Argentina/Buenos Aires - Argentina (GMT-3)",
        value: "America/Argentina/Buenos_Aires",
    },
    { label: "America/Halifax - Canada (GMT-4)", value: "America/Halifax" },
    { label: "Atlantic/Bermuda - Bermuda (GMT-4)", value: "Atlantic/Bermuda" },
    { label: "America/Thule - Greenland (GMT-4)", value: "America/Thule" },
    { label: "America/Sao Paulo - Brazil (GMT-3)", value: "America/Sao_Paulo" },
    { label: "Antarctica/Palmer - Antarctica (GMT-3)", value: "Antarctica/Palmer" },
    { label: "America/Punta Arenas - Chile (GMT-3)", value: "America/Punta_Arenas" },
    { label: "Atlantic/Stanley - Falkland Islands (GMT-3)", value: "Atlantic/Stanley" },
    { label: "America/Cayenne - French Guiana (GMT-3)", value: "America/Cayenne" },
    { label: "America/Asuncion - Paraguay (GMT-3)", value: "America/Asuncion" },
    { label: "America/Paramaribo - Suriname (GMT-3)", value: "America/Paramaribo" },
    { label: "America/Montevideo - Uruguay (GMT-3)", value: "America/Montevideo" },
    { label: "America/St Johns - Canada (GMT-4:30)", value: "America/St_Johns" },
    { label: "America/Noronha - Brazil (GMT-2)", value: "America/Noronha" },
    {
        label: "Atlantic/South Georgia - South Georgia and the South Sandwich Islands (GMT-2)",
        value: "Atlantic/South_Georgia",
    },
    { label: "America/Miquelon - Saint Pierre and Miquelon (GMT-3)", value: "America/Miquelon" },
    { label: "Atlantic/Cape Verde - Cabo Verde (GMT-1)", value: "Atlantic/Cape_Verde" },
    { label: "America/Nuuk - Greenland (GMT-2)", value: "America/Nuuk" },
    { label: "Atlantic/Azores - Portugal (GMT-1)", value: "Atlantic/Azores" },
    { label: "Africa/Abidjan - Ivory Coast (GMT+0)", value: "Africa/Abidjan" },
    { label: "Africa/Bamako - Mali (GMT+0)", value: "Africa/Bamako" },
    { label: "Africa/Bissau - Guinea-Bissau (GMT+0)", value: "Africa/Bissau" },
    { label: "Africa/Conakry - Guinea (GMT+0)", value: "Africa/Conakry" },
    { label: "Africa/Dakar - Senegal (GMT+0)", value: "Africa/Dakar" },
    { label: "America/Danmarkshavn - Greenland (GMT+0)", value: "America/Danmarkshavn" },
    { label: "Africa/Freetown - Sierra Leone (GMT+0)", value: "Africa/Freetown" },
    { label: "Atlantic/St Helena - Saint Helena (GMT+0)", value: "Atlantic/St_Helena" },
    { label: "Africa/Accra - Ghana (GMT+0)", value: "Africa/Accra" },
    { label: "Africa/Lome - Togo (GMT+0)", value: "Africa/Lome" },
    { label: "Africa/Monrovia - Liberia (GMT+0)", value: "Africa/Monrovia" },
    { label: "Africa/Nouakchott - Mauritania (GMT+0)", value: "Africa/Nouakchott" },
    { label: "Africa/Ouagadougou - Burkina Faso (GMT+0)", value: "Africa/Ouagadougou" },
    { label: "Atlantic/Reykjavik - Iceland (GMT+0)", value: "Atlantic/Reykjavik" },
    { label: "Africa/Sao Tome - Sao Tome and Principe (GMT+0)", value: "Africa/Sao_Tome" },
    { label: "Africa/Banjul - Gambia (GMT+0)", value: "Africa/Banjul" },
    { label: "Africa/Algiers - Algeria (GMT+1)", value: "Africa/Algiers" },
    { label: "Africa/Tunis - Tunisia (GMT+1)", value: "Africa/Tunis" },
    { label: "Europe/Isle of Man - Isle of Man (GMT+0)", value: "Europe/Isle_of_Man" },
    { label: "Europe/Dublin - Ireland (GMT+0)", value: "Europe/Dublin" },
    { label: "Europe/London - United Kingdom (GMT+0)", value: "Europe/London" },
    { label: "Europe/Jersey - Jersey (GMT+0)", value: "Europe/Jersey" },
    { label: "Europe/Guernsey - Guernsey (GMT+0)", value: "Europe/Guernsey" },
    { label: "Africa/Bangui - Central African Republic (GMT+1)", value: "Africa/Bangui" },
    { label: "Africa/Malabo - Equatorial Guinea (GMT+1)", value: "Africa/Malabo" },
    { label: "Africa/Brazzaville - Republic of the Congo (GMT+1)", value: "Africa/Brazzaville" },
    { label: "Africa/Porto-Novo - Benin (GMT+1)", value: "Africa/Porto-Novo" },
    { label: "Africa/Douala - Cameroon (GMT+1)", value: "Africa/Douala" },
    {
        label: "Africa/Kinshasa - Democratic Republic of the Congo (GMT+1)",
        value: "Africa/Kinshasa",
    },
    { label: "Africa/Lagos - Nigeria (GMT+1)", value: "Africa/Lagos" },
    { label: "Africa/Libreville - Gabon (GMT+1)", value: "Africa/Libreville" },
    { label: "Africa/Luanda - Angola (GMT+1)", value: "Africa/Luanda" },
    { label: "Africa/Ndjamena - Chad (GMT+1)", value: "Africa/Ndjamena" },
    { label: "Africa/Niamey - Niger (GMT+1)", value: "Africa/Niamey" },
    { label: "Africa/Casablanca - Morocco (GMT+0)", value: "Africa/Casablanca" },
    { label: "Africa/El Aaiun - Western Sahara (GMT+0)", value: "Africa/El_Aaiun" },
    { label: "Atlantic/Canary - Spain (GMT+0)", value: "Atlantic/Canary" },
    { label: "Europe/Lisbon - Portugal (GMT+0)", value: "Europe/Lisbon" },
    { label: "Atlantic/Faroe - Faroe Islands (GMT+0)", value: "Atlantic/Faroe" },
    { label: "Africa/Bujumbura - Burundi (GMT+2)", value: "Africa/Bujumbura" },
    { label: "Africa/Gaborone - Botswana (GMT+2)", value: "Africa/Gaborone" },
    { label: "Africa/Harare - Zimbabwe (GMT+2)", value: "Africa/Harare" },
    { label: "Africa/Juba - South Sudan (GMT+2)", value: "Africa/Juba" },
    { label: "Africa/Khartoum - Sudan (GMT+2)", value: "Africa/Khartoum" },
    { label: "Africa/Kigali - Rwanda (GMT+2)", value: "Africa/Kigali" },
    { label: "Africa/Blantyre - Malawi (GMT+2)", value: "Africa/Blantyre" },
    {
        label: "Africa/Lubumbashi - Democratic Republic of the Congo (GMT+2)",
        value: "Africa/Lubumbashi",
    },
    { label: "Africa/Lusaka - Zambia (GMT+2)", value: "Africa/Lusaka" },
    { label: "Africa/Maputo - Mozambique (GMT+2)", value: "Africa/Maputo" },
    { label: "Africa/Windhoek - Namibia (GMT+1)", value: "Africa/Windhoek" },
    { label: "Europe/Andorra - Andorra (GMT+1)", value: "Europe/Andorra" },
    { label: "Europe/Belgrade - Serbia (GMT+1)", value: "Europe/Belgrade" },
    { label: "Europe/Berlin - Germany (GMT+1)", value: "Europe/Berlin" },
    { label: "Europe/Bratislava - Slovakia (GMT+1)", value: "Europe/Bratislava" },
    { label: "Europe/Brussels - Belgium (GMT+1)", value: "Europe/Brussels" },
    { label: "Europe/Budapest - Hungary (GMT+1)", value: "Europe/Budapest" },
    { label: "Europe/Copenhagen - Denmark (GMT+1)", value: "Europe/Copenhagen" },
    { label: "Europe/Gibraltar - Gibraltar (GMT+1)", value: "Europe/Gibraltar" },
    { label: "Europe/Ljubljana - Slovenia (GMT+1)", value: "Europe/Ljubljana" },
    { label: "Arctic/Longyearbyen - Svalbard and Jan Mayen (GMT+1)", value: "Arctic/Longyearbyen" },
    { label: "Europe/Luxembourg - Luxembourg (GMT+1)", value: "Europe/Luxembourg" },
    { label: "Europe/Madrid - Spain (GMT+1)", value: "Europe/Madrid" },
    { label: "Europe/Monaco - Monaco (GMT+1)", value: "Europe/Monaco" },
    { label: "Europe/Oslo - Norway (GMT+1)", value: "Europe/Oslo" },
    { label: "Europe/Paris - France (GMT+1)", value: "Europe/Paris" },
    { label: "Europe/Podgorica - Montenegro (GMT+1)", value: "Europe/Podgorica" },
    { label: "Europe/Prague - Czechia (GMT+1)", value: "Europe/Prague" },
    { label: "Europe/Rome - Italy (GMT+1)", value: "Europe/Rome" },
    { label: "Europe/Amsterdam - The Netherlands (GMT+1)", value: "Europe/Amsterdam" },
    { label: "Europe/San Marino - San Marino (GMT+1)", value: "Europe/San_Marino" },
    { label: "Europe/Malta - Malta (GMT+1)", value: "Europe/Malta" },
    { label: "Europe/Sarajevo - Bosnia and Herzegovina (GMT+1)", value: "Europe/Sarajevo" },
    { label: "Europe/Skopje - North Macedonia (GMT+1)", value: "Europe/Skopje" },
    { label: "Europe/Stockholm - Sweden (GMT+1)", value: "Europe/Stockholm" },
    { label: "Europe/Tirane - Albania (GMT+1)", value: "Europe/Tirane" },
    { label: "Europe/Vaduz - Liechtenstein (GMT+1)", value: "Europe/Vaduz" },
    { label: "Europe/Vatican - Vatican (GMT+1)", value: "Europe/Vatican" },
    { label: "Europe/Vienna - Austria (GMT+1)", value: "Europe/Vienna" },
    { label: "Europe/Warsaw - Poland (GMT+1)", value: "Europe/Warsaw" },
    { label: "Europe/Zagreb - Croatia (GMT+1)", value: "Europe/Zagreb" },
    { label: "Europe/Zurich - Switzerland (GMT+1)", value: "Europe/Zurich" },
    { label: "Africa/Cairo - Egypt (GMT+2)", value: "Africa/Cairo" },
    { label: "Europe/Kaliningrad - Russia (GMT+2)", value: "Europe/Kaliningrad" },
    { label: "Africa/Tripoli - Libya (GMT+2)", value: "Africa/Tripoli" },
    { label: "Antarctica/Troll - Antarctica (GMT+0)", value: "Antarctica/Troll" },
    { label: "Africa/Johannesburg - South Africa (GMT+2)", value: "Africa/Johannesburg" },
    { label: "Africa/Mbabane - Eswatini (GMT+2)", value: "Africa/Mbabane" },
    { label: "Africa/Maseru - Lesotho (GMT+2)", value: "Africa/Maseru" },
    { label: "Asia/Kuwait - Kuwait (GMT+3)", value: "Asia/Kuwait" },
    { label: "Asia/Bahrain - Bahrain (GMT+3)", value: "Asia/Bahrain" },
    { label: "Asia/Baghdad - Iraq (GMT+3)", value: "Asia/Baghdad" },
    { label: "Asia/Qatar - Qatar (GMT+3)", value: "Asia/Qatar" },
    { label: "Asia/Riyadh - Saudi Arabia (GMT+3)", value: "Asia/Riyadh" },
    { label: "Asia/Aden - Yemen (GMT+3)", value: "Asia/Aden" },
    { label: "Asia/Amman - Jordan (GMT+3)", value: "Asia/Amman" },
    { label: "Asia/Damascus - Syria (GMT+3)", value: "Asia/Damascus" },
    { label: "Africa/Addis Ababa - Ethiopia (GMT+3)", value: "Africa/Addis_Ababa" },
    { label: "Indian/Antananarivo - Madagascar (GMT+3)", value: "Indian/Antananarivo" },
    { label: "Africa/Asmara - Eritrea (GMT+3)", value: "Africa/Asmara" },
    { label: "Africa/Dar es Salaam - Tanzania (GMT+3)", value: "Africa/Dar_es_Salaam" },
    { label: "Africa/Djibouti - Djibouti (GMT+3)", value: "Africa/Djibouti" },
    { label: "Africa/Kampala - Uganda (GMT+3)", value: "Africa/Kampala" },
    { label: "Indian/Mayotte - Mayotte (GMT+3)", value: "Indian/Mayotte" },
    { label: "Africa/Mogadishu - Somalia (GMT+3)", value: "Africa/Mogadishu" },
    { label: "Indian/Comoro - Comoros (GMT+3)", value: "Indian/Comoro" },
    { label: "Africa/Nairobi - Kenya (GMT+3)", value: "Africa/Nairobi" },
    { label: "Europe/Athens - Greece (GMT+2)", value: "Europe/Athens" },
    { label: "Asia/Beirut - Lebanon (GMT+2)", value: "Asia/Beirut" },
    { label: "Europe/Bucharest - Romania (GMT+2)", value: "Europe/Bucharest" },
    { label: "Europe/Chisinau - Moldova (GMT+2)", value: "Europe/Chisinau" },
    { label: "Asia/Hebron - Palestinian Territory (GMT+2)", value: "Asia/Hebron" },
    { label: "Europe/Helsinki - Finland (GMT+2)", value: "Europe/Helsinki" },
    { label: "Europe/Kyiv - Ukraine (GMT+2)", value: "Europe/Kyiv" },
    { label: "Europe/Mariehamn - Aland Islands (GMT+2)", value: "Europe/Mariehamn" },
    { label: "Asia/Nicosia - Cyprus (GMT+2)", value: "Asia/Nicosia" },
    { label: "Europe/Riga - Latvia (GMT+2)", value: "Europe/Riga" },
    { label: "Europe/Sofia - Bulgaria (GMT+2)", value: "Europe/Sofia" },
    { label: "Europe/Tallinn - Estonia (GMT+2)", value: "Europe/Tallinn" },
    { label: "Europe/Vilnius - Lithuania (GMT+2)", value: "Europe/Vilnius" },
    { label: "Asia/Jerusalem - Israel (GMT+2)", value: "Asia/Jerusalem" },
    { label: "Europe/Minsk - Belarus (GMT+3)", value: "Europe/Minsk" },
    { label: "Europe/Moscow - Russia (GMT+3)", value: "Europe/Moscow" },
    { label: "Europe/Simferopol - Ukraine (GMT+3)", value: "Europe/Simferopol" },
    { label: "Antarctica/Syowa - Antarctica (GMT+3)", value: "Antarctica/Syowa" },
    { label: "Europe/Istanbul - Turkey (GMT+3)", value: "Europe/Istanbul" },
    { label: "Asia/Tehran - Iran (GMT+3:30)", value: "Asia/Tehran" },
    { label: "Asia/Yerevan - Armenia (GMT+4)", value: "Asia/Yerevan" },
    { label: "Asia/Baku - Azerbaijan (GMT+4)", value: "Asia/Baku" },
    { label: "Asia/Tbilisi - Georgia (GMT+4)", value: "Asia/Tbilisi" },
    { label: "Asia/Dubai - United Arab Emirates (GMT+4)", value: "Asia/Dubai" },
    { label: "Asia/Muscat - Oman (GMT+4)", value: "Asia/Muscat" },
    { label: "Indian/Mauritius - Mauritius (GMT+4)", value: "Indian/Mauritius" },
    { label: "Indian/Reunion - Reunion (GMT+4)", value: "Indian/Reunion" },
    { label: "Europe/Samara - Russia (GMT+4)", value: "Europe/Samara" },
    { label: "Indian/Mahe - Seychelles (GMT+4)", value: "Indian/Mahe" },
    { label: "Asia/Kabul - Afghanistan (GMT+4:30)", value: "Asia/Kabul" },
    { label: "Indian/Kerguelen - French Southern Territories (GMT+5)", value: "Indian/Kerguelen" },
    { label: "Asia/Almaty - Kazakhstan (GMT+5)", value: "Asia/Almaty" },
    { label: "Indian/Maldives - Maldives (GMT+5)", value: "Indian/Maldives" },
    { label: "Antarctica/Mawson - Antarctica (GMT+5)", value: "Antarctica/Mawson" },
    { label: "Asia/Karachi - Pakistan (GMT+5)", value: "Asia/Karachi" },
    { label: "Asia/Dushanbe - Tajikistan (GMT+5)", value: "Asia/Dushanbe" },
    { label: "Asia/Ashgabat - Turkmenistan (GMT+5)", value: "Asia/Ashgabat" },
    { label: "Asia/Tashkent - Uzbekistan (GMT+5)", value: "Asia/Tashkent" },
    { label: "Asia/Yekaterinburg - Russia (GMT+5)", value: "Asia/Yekaterinburg" },
    { label: "Asia/Colombo - Sri Lanka (GMT+5:30)", value: "Asia/Colombo" },
    { label: "Asia/Kolkata - India (GMT+5:30)", value: "Asia/Kolkata" },
    { label: "Asia/Kathmandu - Nepal (GMT+5:45)", value: "Asia/Kathmandu" },
    { label: "Asia/Dhaka - Bangladesh (GMT+6)", value: "Asia/Dhaka" },
    { label: "Asia/Thimphu - Bhutan (GMT+6)", value: "Asia/Thimphu" },
    { label: "Asia/Urumqi - China (GMT+6)", value: "Asia/Urumqi" },
    { label: "Indian/Chagos - British Indian Ocean Territory (GMT+6)", value: "Indian/Chagos" },
    { label: "Asia/Bishkek - Kyrgyzstan (GMT+6)", value: "Asia/Bishkek" },
    { label: "Asia/Omsk - Russia (GMT+6)", value: "Asia/Omsk" },
    { label: "Indian/Cocos - Cocos Islands (GMT+6:30)", value: "Indian/Cocos" },
    { label: "Asia/Yangon - Myanmar (GMT+6:30)", value: "Asia/Yangon" },
    { label: "Indian/Christmas - Christmas Island (GMT+7)", value: "Indian/Christmas" },
    { label: "Antarctica/Davis - Antarctica (GMT+7)", value: "Antarctica/Davis" },
    { label: "Asia/Hovd - Mongolia (GMT+7)", value: "Asia/Hovd" },
    { label: "Asia/Bangkok - Thailand (GMT+7)", value: "Asia/Bangkok" },
    { label: "Asia/Ho Chi Minh - Vietnam (GMT+7)", value: "Asia/Ho_Chi_Minh" },
    { label: "Asia/Phnom Penh - Cambodia (GMT+7)", value: "Asia/Phnom_Penh" },
    { label: "Asia/Vientiane - Laos (GMT+7)", value: "Asia/Vientiane" },
    { label: "Asia/Novosibirsk - Russia (GMT+7)", value: "Asia/Novosibirsk" },
    { label: "Asia/Jakarta - Indonesia (GMT+7)", value: "Asia/Jakarta" },
    { label: "Antarctica/Casey - Antarctica (GMT+8)", value: "Antarctica/Casey" },
    { label: "Australia/Perth - Australia (GMT+8)", value: "Australia/Perth" },
    { label: "Asia/Brunei - Brunei (GMT+8)", value: "Asia/Brunei" },
    { label: "Asia/Makassar - Indonesia (GMT+8)", value: "Asia/Makassar" },
    { label: "Asia/Macau - Macao (GMT+8)", value: "Asia/Macau" },
    { label: "Asia/Shanghai - China (GMT+8)", value: "Asia/Shanghai" },
    { label: "Asia/Hong Kong - Hong Kong (GMT+8)", value: "Asia/Hong_Kong" },
    { label: "Asia/Irkutsk - Russia (GMT+8)", value: "Asia/Irkutsk" },
    { label: "Asia/Kuala Lumpur - Malaysia (GMT+8)", value: "Asia/Kuala_Lumpur" },
    { label: "Asia/Manila - Philippines (GMT+8)", value: "Asia/Manila" },
    { label: "Asia/Singapore - Singapore (GMT+8)", value: "Asia/Singapore" },
    { label: "Asia/Taipei - Taiwan (GMT+8)", value: "Asia/Taipei" },
    { label: "Asia/Ulaanbaatar - Mongolia (GMT+8)", value: "Asia/Ulaanbaatar" },
    { label: "Australia/Eucla - Australia (GMT+8:45)", value: "Australia/Eucla" },
    { label: "Asia/Jayapura - Indonesia (GMT+9)", value: "Asia/Jayapura" },
    { label: "Asia/Tokyo - Japan (GMT+9)", value: "Asia/Tokyo" },
    { label: "Asia/Pyongyang - North Korea (GMT+9)", value: "Asia/Pyongyang" },
    { label: "Asia/Seoul - South Korea (GMT+9)", value: "Asia/Seoul" },
    { label: "Pacific/Palau - Palau (GMT+9)", value: "Pacific/Palau" },
    { label: "Asia/Dili - Timor Leste (GMT+9)", value: "Asia/Dili" },
    { label: "Asia/Chita - Russia (GMT+9)", value: "Asia/Chita" },
    { label: "Australia/Adelaide - Australia (GMT+9:30)", value: "Australia/Adelaide" },
    { label: "Australia/Darwin - Australia (GMT+9:30)", value: "Australia/Darwin" },
    { label: "Australia/Brisbane - Australia (GMT+10)", value: "Australia/Brisbane" },
    { label: "Australia/Sydney - Australia (GMT+10)", value: "Australia/Sydney" },
    { label: "Pacific/Guam - Guam (GMT+10)", value: "Pacific/Guam" },
    { label: "Pacific/Saipan - Northern Mariana Islands (GMT+10)", value: "Pacific/Saipan" },
    { label: "Pacific/Chuuk - Micronesia (GMT+10)", value: "Pacific/Chuuk" },
    {
        label: "Antarctica/DumontDUrville - Antarctica (GMT+10)",
        value: "Antarctica/DumontDUrville",
    },
    { label: "Pacific/Port Moresby - Papua New Guinea (GMT+10)", value: "Pacific/Port_Moresby" },
    { label: "Asia/Vladivostok - Russia (GMT+10)", value: "Asia/Vladivostok" },
    { label: "Australia/Lord Howe - Australia (GMT+10:30)", value: "Australia/Lord_Howe" },
    { label: "Pacific/Bougainville - Papua New Guinea (GMT+11)", value: "Pacific/Bougainville" },
    { label: "Pacific/Kosrae - Micronesia (GMT+11)", value: "Pacific/Kosrae" },
    { label: "Pacific/Noumea - New Caledonia (GMT+11)", value: "Pacific/Noumea" },
    { label: "Pacific/Norfolk - Norfolk Island (GMT+11)", value: "Pacific/Norfolk" },
    { label: "Asia/Sakhalin - Russia (GMT+11)", value: "Asia/Sakhalin" },
    { label: "Pacific/Guadalcanal - Solomon Islands (GMT+11)", value: "Pacific/Guadalcanal" },
    { label: "Pacific/Efate - Vanuatu (GMT+11)", value: "Pacific/Efate" },
    { label: "Pacific/Fiji - Fiji (GMT+12)", value: "Pacific/Fiji" },
    { label: "Pacific/Tarawa - Kiribati (GMT+12)", value: "Pacific/Tarawa" },
    { label: "Asia/Kamchatka - Russia (GMT+12)", value: "Asia/Kamchatka" },
    { label: "Pacific/Majuro - Marshall Islands (GMT+12)", value: "Pacific/Majuro" },
    { label: "Pacific/Nauru - Nauru (GMT+12)", value: "Pacific/Nauru" },
    { label: "Pacific/Auckland - New Zealand (GMT+12)", value: "Pacific/Auckland" },
    { label: "Antarctica/McMurdo - Antarctica (GMT+12)", value: "Antarctica/McMurdo" },
    { label: "Pacific/Funafuti - Tuvalu (GMT+12)", value: "Pacific/Funafuti" },
    {
        label: "Pacific/Wake - United States Minor Outlying Islands (GMT+12)",
        value: "Pacific/Wake",
    },
    { label: "Pacific/Wallis - Wallis and Futuna (GMT+12)", value: "Pacific/Wallis" },
    { label: "Pacific/Chatham - New Zealand (GMT+12:45)", value: "Pacific/Chatham" },
    { label: "Pacific/Kanton - Kiribati (GMT+13)", value: "Pacific/Kanton" },
    { label: "Pacific/Apia - Samoa (GMT+13)", value: "Pacific/Apia" },
    { label: "Pacific/Fakaofo - Tokelau (GMT+13)", value: "Pacific/Fakaofo" },
    { label: "Pacific/Tongatapu - Tonga (GMT+13)", value: "Pacific/Tongatapu" },
    { label: "Pacific/Kiritimati - Kiribati (GMT+14)", value: "Pacific/Kiritimati" },
] as const;

export type TimezoneValue = (typeof const_TimezoneOptions)[number]["value"];
