/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthInvitationRouteImport } from './routes/_auth/invitation'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedOrganizationIdRouteRouteImport } from './routes/_protected/$organizationId/route'
import { Route as ProtectedOrganizationIdIndexRouteImport } from './routes/_protected/$organizationId/index'
import { Route as ProtectedOnboardingInvitationTokenRouteImport } from './routes/_protected/onboarding/$invitationToken'
import { Route as ProtectedOrganizationIdTimesheetsIndexRouteImport } from './routes/_protected/$organizationId/timesheets/index'
import { Route as ProtectedOrganizationIdOrgChartIndexRouteImport } from './routes/_protected/$organizationId/org-chart/index'
import { Route as ProtectedOrganizationIdMyTimeclockIndexRouteImport } from './routes/_protected/$organizationId/my-timeclock/index'
import { Route as ProtectedOrganizationIdEmployeesIndexRouteImport } from './routes/_protected/$organizationId/employees/index'
import { Route as ProtectedOrganizationIdAppsTasksRouteImport } from './routes/_protected/$organizationId/apps/tasks'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvitationRoute = AuthInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedOrganizationIdRouteRoute =
  ProtectedOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationIdIndexRoute =
  ProtectedOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOnboardingInvitationTokenRoute =
  ProtectedOnboardingInvitationTokenRouteImport.update({
    id: '/onboarding/$invitationToken',
    path: '/onboarding/$invitationToken',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationIdTimesheetsIndexRoute =
  ProtectedOrganizationIdTimesheetsIndexRouteImport.update({
    id: '/timesheets/',
    path: '/timesheets/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdOrgChartIndexRoute =
  ProtectedOrganizationIdOrgChartIndexRouteImport.update({
    id: '/org-chart/',
    path: '/org-chart/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdMyTimeclockIndexRoute =
  ProtectedOrganizationIdMyTimeclockIndexRouteImport.update({
    id: '/my-timeclock/',
    path: '/my-timeclock/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdEmployeesIndexRoute =
  ProtectedOrganizationIdEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdAppsTasksRoute =
  ProtectedOrganizationIdAppsTasksRouteImport.update({
    id: '/apps/tasks',
    path: '/apps/tasks',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/$organizationId': typeof ProtectedOrganizationIdRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitation': typeof AuthInvitationRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/$invitationToken': typeof ProtectedOnboardingInvitationTokenRoute
  '/$organizationId/': typeof ProtectedOrganizationIdIndexRoute
  '/$organizationId/apps/tasks': typeof ProtectedOrganizationIdAppsTasksRoute
  '/$organizationId/employees/': typeof ProtectedOrganizationIdEmployeesIndexRoute
  '/$organizationId/my-timeclock/': typeof ProtectedOrganizationIdMyTimeclockIndexRoute
  '/$organizationId/org-chart/': typeof ProtectedOrganizationIdOrgChartIndexRoute
  '/$organizationId/timesheets/': typeof ProtectedOrganizationIdTimesheetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitation': typeof AuthInvitationRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/$invitationToken': typeof ProtectedOnboardingInvitationTokenRoute
  '/$organizationId': typeof ProtectedOrganizationIdIndexRoute
  '/$organizationId/apps/tasks': typeof ProtectedOrganizationIdAppsTasksRoute
  '/$organizationId/employees': typeof ProtectedOrganizationIdEmployeesIndexRoute
  '/$organizationId/my-timeclock': typeof ProtectedOrganizationIdMyTimeclockIndexRoute
  '/$organizationId/org-chart': typeof ProtectedOrganizationIdOrgChartIndexRoute
  '/$organizationId/timesheets': typeof ProtectedOrganizationIdTimesheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/$organizationId': typeof ProtectedOrganizationIdRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/invitation': typeof AuthInvitationRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/onboarding/$invitationToken': typeof ProtectedOnboardingInvitationTokenRoute
  '/_protected/$organizationId/': typeof ProtectedOrganizationIdIndexRoute
  '/_protected/$organizationId/apps/tasks': typeof ProtectedOrganizationIdAppsTasksRoute
  '/_protected/$organizationId/employees/': typeof ProtectedOrganizationIdEmployeesIndexRoute
  '/_protected/$organizationId/my-timeclock/': typeof ProtectedOrganizationIdMyTimeclockIndexRoute
  '/_protected/$organizationId/org-chart/': typeof ProtectedOrganizationIdOrgChartIndexRoute
  '/_protected/$organizationId/timesheets/': typeof ProtectedOrganizationIdTimesheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationId'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/onboarding/$invitationToken'
    | '/$organizationId/'
    | '/$organizationId/apps/tasks'
    | '/$organizationId/employees/'
    | '/$organizationId/my-timeclock/'
    | '/$organizationId/org-chart/'
    | '/$organizationId/timesheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/onboarding/$invitationToken'
    | '/$organizationId'
    | '/$organizationId/apps/tasks'
    | '/$organizationId/employees'
    | '/$organizationId/my-timeclock'
    | '/$organizationId/org-chart'
    | '/$organizationId/timesheets'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_protected/$organizationId'
    | '/_auth/forgot-password'
    | '/_auth/invitation'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_protected/'
    | '/_protected/onboarding/$invitationToken'
    | '/_protected/$organizationId/'
    | '/_protected/$organizationId/apps/tasks'
    | '/_protected/$organizationId/employees/'
    | '/_protected/$organizationId/my-timeclock/'
    | '/_protected/$organizationId/org-chart/'
    | '/_protected/$organizationId/timesheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invitation': {
      id: '/_auth/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof AuthInvitationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/$organizationId': {
      id: '/_protected/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof ProtectedOrganizationIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationId/': {
      id: '/_protected/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof ProtectedOrganizationIdIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/onboarding/$invitationToken': {
      id: '/_protected/onboarding/$invitationToken'
      path: '/onboarding/$invitationToken'
      fullPath: '/onboarding/$invitationToken'
      preLoaderRoute: typeof ProtectedOnboardingInvitationTokenRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationId/timesheets/': {
      id: '/_protected/$organizationId/timesheets/'
      path: '/timesheets'
      fullPath: '/$organizationId/timesheets/'
      preLoaderRoute: typeof ProtectedOrganizationIdTimesheetsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/org-chart/': {
      id: '/_protected/$organizationId/org-chart/'
      path: '/org-chart'
      fullPath: '/$organizationId/org-chart/'
      preLoaderRoute: typeof ProtectedOrganizationIdOrgChartIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/my-timeclock/': {
      id: '/_protected/$organizationId/my-timeclock/'
      path: '/my-timeclock'
      fullPath: '/$organizationId/my-timeclock/'
      preLoaderRoute: typeof ProtectedOrganizationIdMyTimeclockIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/employees/': {
      id: '/_protected/$organizationId/employees/'
      path: '/employees'
      fullPath: '/$organizationId/employees/'
      preLoaderRoute: typeof ProtectedOrganizationIdEmployeesIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/apps/tasks': {
      id: '/_protected/$organizationId/apps/tasks'
      path: '/apps/tasks'
      fullPath: '/$organizationId/apps/tasks'
      preLoaderRoute: typeof ProtectedOrganizationIdAppsTasksRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthInvitationRoute: typeof AuthInvitationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthInvitationRoute: AuthInvitationRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedOrganizationIdRouteRouteChildren {
  ProtectedOrganizationIdIndexRoute: typeof ProtectedOrganizationIdIndexRoute
  ProtectedOrganizationIdAppsTasksRoute: typeof ProtectedOrganizationIdAppsTasksRoute
  ProtectedOrganizationIdEmployeesIndexRoute: typeof ProtectedOrganizationIdEmployeesIndexRoute
  ProtectedOrganizationIdMyTimeclockIndexRoute: typeof ProtectedOrganizationIdMyTimeclockIndexRoute
  ProtectedOrganizationIdOrgChartIndexRoute: typeof ProtectedOrganizationIdOrgChartIndexRoute
  ProtectedOrganizationIdTimesheetsIndexRoute: typeof ProtectedOrganizationIdTimesheetsIndexRoute
}

const ProtectedOrganizationIdRouteRouteChildren: ProtectedOrganizationIdRouteRouteChildren =
  {
    ProtectedOrganizationIdIndexRoute: ProtectedOrganizationIdIndexRoute,
    ProtectedOrganizationIdAppsTasksRoute:
      ProtectedOrganizationIdAppsTasksRoute,
    ProtectedOrganizationIdEmployeesIndexRoute:
      ProtectedOrganizationIdEmployeesIndexRoute,
    ProtectedOrganizationIdMyTimeclockIndexRoute:
      ProtectedOrganizationIdMyTimeclockIndexRoute,
    ProtectedOrganizationIdOrgChartIndexRoute:
      ProtectedOrganizationIdOrgChartIndexRoute,
    ProtectedOrganizationIdTimesheetsIndexRoute:
      ProtectedOrganizationIdTimesheetsIndexRoute,
  }

const ProtectedOrganizationIdRouteRouteWithChildren =
  ProtectedOrganizationIdRouteRoute._addFileChildren(
    ProtectedOrganizationIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedOrganizationIdRouteRoute: typeof ProtectedOrganizationIdRouteRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedOnboardingInvitationTokenRoute: typeof ProtectedOnboardingInvitationTokenRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOrganizationIdRouteRoute:
    ProtectedOrganizationIdRouteRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedOnboardingInvitationTokenRoute:
    ProtectedOnboardingInvitationTokenRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
