/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteRouteImport } from './routes/embed/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PublicVerifyRouteImport } from './routes/_public/verify'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthPendingAccessRouteImport } from './routes/_auth/pending-access'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthInvitationRouteImport } from './routes/_auth/invitation'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedMeRouteRouteImport } from './routes/_protected/me/route'
import { Route as ProtectedOrganizationIdRouteRouteImport } from './routes/_protected/$organizationId/route'
import { Route as ProtectedOrganizationIdIndexRouteImport } from './routes/_protected/$organizationId/index'
import { Route as EmbedSignAccessTokenRouteImport } from './routes/embed/sign.$accessToken'
import { Route as PublicSignAccessTokenRouteImport } from './routes/_public/sign.$accessToken'
import { Route as ProtectedOrganizationIdSettingsRouteRouteImport } from './routes/_protected/$organizationId/settings/route'
import { Route as ProtectedMeDocumentsIndexRouteImport } from './routes/_protected/me/documents/index'
import { Route as ProtectedOrganizationIdTemplatesIndexRouteImport } from './routes/_protected/$organizationId/templates/index'
import { Route as ProtectedOrganizationIdSettingsIndexRouteImport } from './routes/_protected/$organizationId/settings/index'
import { Route as ProtectedOrganizationIdPeopleIndexRouteImport } from './routes/_protected/$organizationId/people/index'
import { Route as ProtectedOrganizationIdNotificationsIndexRouteImport } from './routes/_protected/$organizationId/notifications/index'
import { Route as ProtectedOrganizationIdEnvelopesIndexRouteImport } from './routes/_protected/$organizationId/envelopes/index'
import { Route as ProtectedOrganizationIdArchiveIndexRouteImport } from './routes/_protected/$organizationId/archive/index'
import { Route as ProtectedMeDocumentsNewRouteImport } from './routes/_protected/me/documents/new'
import { Route as ProtectedOrganizationIdTemplatesTemplateIdRouteImport } from './routes/_protected/$organizationId/templates/$templateId'
import { Route as ProtectedOrganizationIdSettingsGeneralRouteImport } from './routes/_protected/$organizationId/settings/general'
import { Route as ProtectedOrganizationIdSettingsDocumentsRouteImport } from './routes/_protected/$organizationId/settings/documents'
import { Route as ProtectedOrganizationIdSettingsDangerRouteImport } from './routes/_protected/$organizationId/settings/danger'
import { Route as ProtectedOrganizationIdSettingsBrandingRouteImport } from './routes/_protected/$organizationId/settings/branding'
import { Route as ProtectedOrganizationIdSettingsBillingRouteImport } from './routes/_protected/$organizationId/settings/billing'
import { Route as ProtectedOrganizationIdEnvelopesNewRouteImport } from './routes/_protected/$organizationId/envelopes/new'
import { Route as ProtectedOrganizationIdSettingsIntegrationsRouteRouteImport } from './routes/_protected/$organizationId/settings/_integrations/route'
import { Route as ProtectedMeDocumentsEnvelopeIdIndexRouteImport } from './routes/_protected/me/documents/$envelopeId.index'
import { Route as ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRouteImport } from './routes/_protected/$organizationId/envelopes/$envelopeId.index'
import { Route as ProtectedMeDocumentsEnvelopeIdEditRouteImport } from './routes/_protected/me/documents/$envelopeId.edit'
import { Route as ProtectedOrganizationIdSettingsIntegrationsWebhooksRouteImport } from './routes/_protected/$organizationId/settings/_integrations/webhooks'
import { Route as ProtectedOrganizationIdSettingsIntegrationsApiKeysRouteImport } from './routes/_protected/$organizationId/settings/_integrations/api-keys'
import { Route as ProtectedOrganizationIdEnvelopesEnvelopeIdEditRouteImport } from './routes/_protected/$organizationId/envelopes/$envelopeId.edit'

const EmbedRouteRoute = EmbedRouteRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyRoute = PublicVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPendingAccessRoute = AuthPendingAccessRouteImport.update({
  id: '/pending-access',
  path: '/pending-access',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvitationRoute = AuthInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedMeRouteRoute = ProtectedMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrganizationIdRouteRoute =
  ProtectedOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationIdIndexRoute =
  ProtectedOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const EmbedSignAccessTokenRoute = EmbedSignAccessTokenRouteImport.update({
  id: '/sign/$accessToken',
  path: '/sign/$accessToken',
  getParentRoute: () => EmbedRouteRoute,
} as any)
const PublicSignAccessTokenRoute = PublicSignAccessTokenRouteImport.update({
  id: '/sign/$accessToken',
  path: '/sign/$accessToken',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedOrganizationIdSettingsRouteRoute =
  ProtectedOrganizationIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedMeDocumentsIndexRoute =
  ProtectedMeDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => ProtectedMeRouteRoute,
  } as any)
const ProtectedOrganizationIdTemplatesIndexRoute =
  ProtectedOrganizationIdTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsIndexRoute =
  ProtectedOrganizationIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdPeopleIndexRoute =
  ProtectedOrganizationIdPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdNotificationsIndexRoute =
  ProtectedOrganizationIdNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdEnvelopesIndexRoute =
  ProtectedOrganizationIdEnvelopesIndexRouteImport.update({
    id: '/envelopes/',
    path: '/envelopes/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdArchiveIndexRoute =
  ProtectedOrganizationIdArchiveIndexRouteImport.update({
    id: '/archive/',
    path: '/archive/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedMeDocumentsNewRoute = ProtectedMeDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => ProtectedMeRouteRoute,
} as any)
const ProtectedOrganizationIdTemplatesTemplateIdRoute =
  ProtectedOrganizationIdTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsGeneralRoute =
  ProtectedOrganizationIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsDocumentsRoute =
  ProtectedOrganizationIdSettingsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsDangerRoute =
  ProtectedOrganizationIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsBrandingRoute =
  ProtectedOrganizationIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsBillingRoute =
  ProtectedOrganizationIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedOrganizationIdEnvelopesNewRoute =
  ProtectedOrganizationIdEnvelopesNewRouteImport.update({
    id: '/envelopes/new',
    path: '/envelopes/new',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsIntegrationsRouteRoute =
  ProtectedOrganizationIdSettingsIntegrationsRouteRouteImport.update({
    id: '/_integrations',
    getParentRoute: () => ProtectedOrganizationIdSettingsRouteRoute,
  } as any)
const ProtectedMeDocumentsEnvelopeIdIndexRoute =
  ProtectedMeDocumentsEnvelopeIdIndexRouteImport.update({
    id: '/documents/$envelopeId/',
    path: '/documents/$envelopeId/',
    getParentRoute: () => ProtectedMeRouteRoute,
  } as any)
const ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute =
  ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRouteImport.update({
    id: '/envelopes/$envelopeId/',
    path: '/envelopes/$envelopeId/',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)
const ProtectedMeDocumentsEnvelopeIdEditRoute =
  ProtectedMeDocumentsEnvelopeIdEditRouteImport.update({
    id: '/documents/$envelopeId/edit',
    path: '/documents/$envelopeId/edit',
    getParentRoute: () => ProtectedMeRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute =
  ProtectedOrganizationIdSettingsIntegrationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => ProtectedOrganizationIdSettingsIntegrationsRouteRoute,
  } as any)
const ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute =
  ProtectedOrganizationIdSettingsIntegrationsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => ProtectedOrganizationIdSettingsIntegrationsRouteRoute,
  } as any)
const ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute =
  ProtectedOrganizationIdEnvelopesEnvelopeIdEditRouteImport.update({
    id: '/envelopes/$envelopeId/edit',
    path: '/envelopes/$envelopeId/edit',
    getParentRoute: () => ProtectedOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/embed': typeof EmbedRouteRouteWithChildren
  '/$organizationId': typeof ProtectedOrganizationIdRouteRouteWithChildren
  '/me': typeof ProtectedMeRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitation': typeof AuthInvitationRoute
  '/login': typeof AuthLoginRoute
  '/pending-access': typeof AuthPendingAccessRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/settings': typeof ProtectedSettingsRoute
  '/verify': typeof PublicVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationId/settings': typeof ProtectedOrganizationIdSettingsIntegrationsRouteRouteWithChildren
  '/sign/$accessToken': typeof PublicSignAccessTokenRoute
  '/embed/sign/$accessToken': typeof EmbedSignAccessTokenRoute
  '/$organizationId/': typeof ProtectedOrganizationIdIndexRoute
  '/$organizationId/envelopes/new': typeof ProtectedOrganizationIdEnvelopesNewRoute
  '/$organizationId/settings/billing': typeof ProtectedOrganizationIdSettingsBillingRoute
  '/$organizationId/settings/branding': typeof ProtectedOrganizationIdSettingsBrandingRoute
  '/$organizationId/settings/danger': typeof ProtectedOrganizationIdSettingsDangerRoute
  '/$organizationId/settings/documents': typeof ProtectedOrganizationIdSettingsDocumentsRoute
  '/$organizationId/settings/general': typeof ProtectedOrganizationIdSettingsGeneralRoute
  '/$organizationId/templates/$templateId': typeof ProtectedOrganizationIdTemplatesTemplateIdRoute
  '/me/documents/new': typeof ProtectedMeDocumentsNewRoute
  '/$organizationId/archive/': typeof ProtectedOrganizationIdArchiveIndexRoute
  '/$organizationId/envelopes/': typeof ProtectedOrganizationIdEnvelopesIndexRoute
  '/$organizationId/notifications/': typeof ProtectedOrganizationIdNotificationsIndexRoute
  '/$organizationId/people/': typeof ProtectedOrganizationIdPeopleIndexRoute
  '/$organizationId/settings/': typeof ProtectedOrganizationIdSettingsIndexRoute
  '/$organizationId/templates/': typeof ProtectedOrganizationIdTemplatesIndexRoute
  '/me/documents/': typeof ProtectedMeDocumentsIndexRoute
  '/$organizationId/envelopes/$envelopeId/edit': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute
  '/$organizationId/settings/api-keys': typeof ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute
  '/$organizationId/settings/webhooks': typeof ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute
  '/me/documents/$envelopeId/edit': typeof ProtectedMeDocumentsEnvelopeIdEditRoute
  '/$organizationId/envelopes/$envelopeId/': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute
  '/me/documents/$envelopeId/': typeof ProtectedMeDocumentsEnvelopeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/embed': typeof EmbedRouteRouteWithChildren
  '/me': typeof ProtectedMeRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitation': typeof AuthInvitationRoute
  '/login': typeof AuthLoginRoute
  '/pending-access': typeof AuthPendingAccessRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/settings': typeof ProtectedSettingsRoute
  '/verify': typeof PublicVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sign/$accessToken': typeof PublicSignAccessTokenRoute
  '/embed/sign/$accessToken': typeof EmbedSignAccessTokenRoute
  '/$organizationId': typeof ProtectedOrganizationIdIndexRoute
  '/$organizationId/settings': typeof ProtectedOrganizationIdSettingsIndexRoute
  '/$organizationId/envelopes/new': typeof ProtectedOrganizationIdEnvelopesNewRoute
  '/$organizationId/settings/billing': typeof ProtectedOrganizationIdSettingsBillingRoute
  '/$organizationId/settings/branding': typeof ProtectedOrganizationIdSettingsBrandingRoute
  '/$organizationId/settings/danger': typeof ProtectedOrganizationIdSettingsDangerRoute
  '/$organizationId/settings/documents': typeof ProtectedOrganizationIdSettingsDocumentsRoute
  '/$organizationId/settings/general': typeof ProtectedOrganizationIdSettingsGeneralRoute
  '/$organizationId/templates/$templateId': typeof ProtectedOrganizationIdTemplatesTemplateIdRoute
  '/me/documents/new': typeof ProtectedMeDocumentsNewRoute
  '/$organizationId/archive': typeof ProtectedOrganizationIdArchiveIndexRoute
  '/$organizationId/envelopes': typeof ProtectedOrganizationIdEnvelopesIndexRoute
  '/$organizationId/notifications': typeof ProtectedOrganizationIdNotificationsIndexRoute
  '/$organizationId/people': typeof ProtectedOrganizationIdPeopleIndexRoute
  '/$organizationId/templates': typeof ProtectedOrganizationIdTemplatesIndexRoute
  '/me/documents': typeof ProtectedMeDocumentsIndexRoute
  '/$organizationId/envelopes/$envelopeId/edit': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute
  '/$organizationId/settings/api-keys': typeof ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute
  '/$organizationId/settings/webhooks': typeof ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute
  '/me/documents/$envelopeId/edit': typeof ProtectedMeDocumentsEnvelopeIdEditRoute
  '/$organizationId/envelopes/$envelopeId': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute
  '/me/documents/$envelopeId': typeof ProtectedMeDocumentsEnvelopeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/embed': typeof EmbedRouteRouteWithChildren
  '/_protected/$organizationId': typeof ProtectedOrganizationIdRouteRouteWithChildren
  '/_protected/me': typeof ProtectedMeRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/invitation': typeof AuthInvitationRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/pending-access': typeof AuthPendingAccessRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/verify': typeof PublicVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/$organizationId/settings': typeof ProtectedOrganizationIdSettingsRouteRouteWithChildren
  '/_public/sign/$accessToken': typeof PublicSignAccessTokenRoute
  '/embed/sign/$accessToken': typeof EmbedSignAccessTokenRoute
  '/_protected/$organizationId/': typeof ProtectedOrganizationIdIndexRoute
  '/_protected/$organizationId/settings/_integrations': typeof ProtectedOrganizationIdSettingsIntegrationsRouteRouteWithChildren
  '/_protected/$organizationId/envelopes/new': typeof ProtectedOrganizationIdEnvelopesNewRoute
  '/_protected/$organizationId/settings/billing': typeof ProtectedOrganizationIdSettingsBillingRoute
  '/_protected/$organizationId/settings/branding': typeof ProtectedOrganizationIdSettingsBrandingRoute
  '/_protected/$organizationId/settings/danger': typeof ProtectedOrganizationIdSettingsDangerRoute
  '/_protected/$organizationId/settings/documents': typeof ProtectedOrganizationIdSettingsDocumentsRoute
  '/_protected/$organizationId/settings/general': typeof ProtectedOrganizationIdSettingsGeneralRoute
  '/_protected/$organizationId/templates/$templateId': typeof ProtectedOrganizationIdTemplatesTemplateIdRoute
  '/_protected/me/documents/new': typeof ProtectedMeDocumentsNewRoute
  '/_protected/$organizationId/archive/': typeof ProtectedOrganizationIdArchiveIndexRoute
  '/_protected/$organizationId/envelopes/': typeof ProtectedOrganizationIdEnvelopesIndexRoute
  '/_protected/$organizationId/notifications/': typeof ProtectedOrganizationIdNotificationsIndexRoute
  '/_protected/$organizationId/people/': typeof ProtectedOrganizationIdPeopleIndexRoute
  '/_protected/$organizationId/settings/': typeof ProtectedOrganizationIdSettingsIndexRoute
  '/_protected/$organizationId/templates/': typeof ProtectedOrganizationIdTemplatesIndexRoute
  '/_protected/me/documents/': typeof ProtectedMeDocumentsIndexRoute
  '/_protected/$organizationId/envelopes/$envelopeId/edit': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute
  '/_protected/$organizationId/settings/_integrations/api-keys': typeof ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute
  '/_protected/$organizationId/settings/_integrations/webhooks': typeof ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute
  '/_protected/me/documents/$envelopeId/edit': typeof ProtectedMeDocumentsEnvelopeIdEditRoute
  '/_protected/$organizationId/envelopes/$envelopeId/': typeof ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute
  '/_protected/me/documents/$envelopeId/': typeof ProtectedMeDocumentsEnvelopeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/$organizationId'
    | '/me'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/pending-access'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/settings'
    | '/verify'
    | '/auth/callback'
    | '/$organizationId/settings'
    | '/sign/$accessToken'
    | '/embed/sign/$accessToken'
    | '/$organizationId/'
    | '/$organizationId/envelopes/new'
    | '/$organizationId/settings/billing'
    | '/$organizationId/settings/branding'
    | '/$organizationId/settings/danger'
    | '/$organizationId/settings/documents'
    | '/$organizationId/settings/general'
    | '/$organizationId/templates/$templateId'
    | '/me/documents/new'
    | '/$organizationId/archive/'
    | '/$organizationId/envelopes/'
    | '/$organizationId/notifications/'
    | '/$organizationId/people/'
    | '/$organizationId/settings/'
    | '/$organizationId/templates/'
    | '/me/documents/'
    | '/$organizationId/envelopes/$envelopeId/edit'
    | '/$organizationId/settings/api-keys'
    | '/$organizationId/settings/webhooks'
    | '/me/documents/$envelopeId/edit'
    | '/$organizationId/envelopes/$envelopeId/'
    | '/me/documents/$envelopeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/me'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/pending-access'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/settings'
    | '/verify'
    | '/auth/callback'
    | '/sign/$accessToken'
    | '/embed/sign/$accessToken'
    | '/$organizationId'
    | '/$organizationId/settings'
    | '/$organizationId/envelopes/new'
    | '/$organizationId/settings/billing'
    | '/$organizationId/settings/branding'
    | '/$organizationId/settings/danger'
    | '/$organizationId/settings/documents'
    | '/$organizationId/settings/general'
    | '/$organizationId/templates/$templateId'
    | '/me/documents/new'
    | '/$organizationId/archive'
    | '/$organizationId/envelopes'
    | '/$organizationId/notifications'
    | '/$organizationId/people'
    | '/$organizationId/templates'
    | '/me/documents'
    | '/$organizationId/envelopes/$envelopeId/edit'
    | '/$organizationId/settings/api-keys'
    | '/$organizationId/settings/webhooks'
    | '/me/documents/$envelopeId/edit'
    | '/$organizationId/envelopes/$envelopeId'
    | '/me/documents/$envelopeId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/embed'
    | '/_protected/$organizationId'
    | '/_protected/me'
    | '/_auth/forgot-password'
    | '/_auth/invitation'
    | '/_auth/login'
    | '/_auth/pending-access'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_protected/settings'
    | '/_public/verify'
    | '/auth/callback'
    | '/_protected/'
    | '/_protected/$organizationId/settings'
    | '/_public/sign/$accessToken'
    | '/embed/sign/$accessToken'
    | '/_protected/$organizationId/'
    | '/_protected/$organizationId/settings/_integrations'
    | '/_protected/$organizationId/envelopes/new'
    | '/_protected/$organizationId/settings/billing'
    | '/_protected/$organizationId/settings/branding'
    | '/_protected/$organizationId/settings/danger'
    | '/_protected/$organizationId/settings/documents'
    | '/_protected/$organizationId/settings/general'
    | '/_protected/$organizationId/templates/$templateId'
    | '/_protected/me/documents/new'
    | '/_protected/$organizationId/archive/'
    | '/_protected/$organizationId/envelopes/'
    | '/_protected/$organizationId/notifications/'
    | '/_protected/$organizationId/people/'
    | '/_protected/$organizationId/settings/'
    | '/_protected/$organizationId/templates/'
    | '/_protected/me/documents/'
    | '/_protected/$organizationId/envelopes/$envelopeId/edit'
    | '/_protected/$organizationId/settings/_integrations/api-keys'
    | '/_protected/$organizationId/settings/_integrations/webhooks'
    | '/_protected/me/documents/$envelopeId/edit'
    | '/_protected/$organizationId/envelopes/$envelopeId/'
    | '/_protected/me/documents/$envelopeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  EmbedRouteRoute: typeof EmbedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify': {
      id: '/_public/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof PublicVerifyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/pending-access': {
      id: '/_auth/pending-access'
      path: '/pending-access'
      fullPath: '/pending-access'
      preLoaderRoute: typeof AuthPendingAccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invitation': {
      id: '/_auth/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof AuthInvitationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/me': {
      id: '/_protected/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ProtectedMeRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationId': {
      id: '/_protected/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof ProtectedOrganizationIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationId/': {
      id: '/_protected/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof ProtectedOrganizationIdIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/embed/sign/$accessToken': {
      id: '/embed/sign/$accessToken'
      path: '/sign/$accessToken'
      fullPath: '/embed/sign/$accessToken'
      preLoaderRoute: typeof EmbedSignAccessTokenRouteImport
      parentRoute: typeof EmbedRouteRoute
    }
    '/_public/sign/$accessToken': {
      id: '/_public/sign/$accessToken'
      path: '/sign/$accessToken'
      fullPath: '/sign/$accessToken'
      preLoaderRoute: typeof PublicSignAccessTokenRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/$organizationId/settings': {
      id: '/_protected/$organizationId/settings'
      path: '/settings'
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsRouteRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/me/documents/': {
      id: '/_protected/me/documents/'
      path: '/documents'
      fullPath: '/me/documents/'
      preLoaderRoute: typeof ProtectedMeDocumentsIndexRouteImport
      parentRoute: typeof ProtectedMeRouteRoute
    }
    '/_protected/$organizationId/templates/': {
      id: '/_protected/$organizationId/templates/'
      path: '/templates'
      fullPath: '/$organizationId/templates/'
      preLoaderRoute: typeof ProtectedOrganizationIdTemplatesIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/settings/': {
      id: '/_protected/$organizationId/settings/'
      path: '/'
      fullPath: '/$organizationId/settings/'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/people/': {
      id: '/_protected/$organizationId/people/'
      path: '/people'
      fullPath: '/$organizationId/people/'
      preLoaderRoute: typeof ProtectedOrganizationIdPeopleIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/notifications/': {
      id: '/_protected/$organizationId/notifications/'
      path: '/notifications'
      fullPath: '/$organizationId/notifications/'
      preLoaderRoute: typeof ProtectedOrganizationIdNotificationsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/envelopes/': {
      id: '/_protected/$organizationId/envelopes/'
      path: '/envelopes'
      fullPath: '/$organizationId/envelopes/'
      preLoaderRoute: typeof ProtectedOrganizationIdEnvelopesIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/archive/': {
      id: '/_protected/$organizationId/archive/'
      path: '/archive'
      fullPath: '/$organizationId/archive/'
      preLoaderRoute: typeof ProtectedOrganizationIdArchiveIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/me/documents/new': {
      id: '/_protected/me/documents/new'
      path: '/documents/new'
      fullPath: '/me/documents/new'
      preLoaderRoute: typeof ProtectedMeDocumentsNewRouteImport
      parentRoute: typeof ProtectedMeRouteRoute
    }
    '/_protected/$organizationId/templates/$templateId': {
      id: '/_protected/$organizationId/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/$organizationId/templates/$templateId'
      preLoaderRoute: typeof ProtectedOrganizationIdTemplatesTemplateIdRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/settings/general': {
      id: '/_protected/$organizationId/settings/general'
      path: '/general'
      fullPath: '/$organizationId/settings/general'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsGeneralRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/settings/documents': {
      id: '/_protected/$organizationId/settings/documents'
      path: '/documents'
      fullPath: '/$organizationId/settings/documents'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsDocumentsRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/settings/danger': {
      id: '/_protected/$organizationId/settings/danger'
      path: '/danger'
      fullPath: '/$organizationId/settings/danger'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsDangerRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/settings/branding': {
      id: '/_protected/$organizationId/settings/branding'
      path: '/branding'
      fullPath: '/$organizationId/settings/branding'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsBrandingRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/settings/billing': {
      id: '/_protected/$organizationId/settings/billing'
      path: '/billing'
      fullPath: '/$organizationId/settings/billing'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsBillingRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/$organizationId/envelopes/new': {
      id: '/_protected/$organizationId/envelopes/new'
      path: '/envelopes/new'
      fullPath: '/$organizationId/envelopes/new'
      preLoaderRoute: typeof ProtectedOrganizationIdEnvelopesNewRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/$organizationId/settings/_integrations': {
      id: '/_protected/$organizationId/settings/_integrations'
      path: ''
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsIntegrationsRouteRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsRouteRoute
    }
    '/_protected/me/documents/$envelopeId/': {
      id: '/_protected/me/documents/$envelopeId/'
      path: '/documents/$envelopeId'
      fullPath: '/me/documents/$envelopeId/'
      preLoaderRoute: typeof ProtectedMeDocumentsEnvelopeIdIndexRouteImport
      parentRoute: typeof ProtectedMeRouteRoute
    }
    '/_protected/$organizationId/envelopes/$envelopeId/': {
      id: '/_protected/$organizationId/envelopes/$envelopeId/'
      path: '/envelopes/$envelopeId'
      fullPath: '/$organizationId/envelopes/$envelopeId/'
      preLoaderRoute: typeof ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
    '/_protected/me/documents/$envelopeId/edit': {
      id: '/_protected/me/documents/$envelopeId/edit'
      path: '/documents/$envelopeId/edit'
      fullPath: '/me/documents/$envelopeId/edit'
      preLoaderRoute: typeof ProtectedMeDocumentsEnvelopeIdEditRouteImport
      parentRoute: typeof ProtectedMeRouteRoute
    }
    '/_protected/$organizationId/settings/_integrations/webhooks': {
      id: '/_protected/$organizationId/settings/_integrations/webhooks'
      path: '/webhooks'
      fullPath: '/$organizationId/settings/webhooks'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsIntegrationsWebhooksRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsIntegrationsRouteRoute
    }
    '/_protected/$organizationId/settings/_integrations/api-keys': {
      id: '/_protected/$organizationId/settings/_integrations/api-keys'
      path: '/api-keys'
      fullPath: '/$organizationId/settings/api-keys'
      preLoaderRoute: typeof ProtectedOrganizationIdSettingsIntegrationsApiKeysRouteImport
      parentRoute: typeof ProtectedOrganizationIdSettingsIntegrationsRouteRoute
    }
    '/_protected/$organizationId/envelopes/$envelopeId/edit': {
      id: '/_protected/$organizationId/envelopes/$envelopeId/edit'
      path: '/envelopes/$envelopeId/edit'
      fullPath: '/$organizationId/envelopes/$envelopeId/edit'
      preLoaderRoute: typeof ProtectedOrganizationIdEnvelopesEnvelopeIdEditRouteImport
      parentRoute: typeof ProtectedOrganizationIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthInvitationRoute: typeof AuthInvitationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPendingAccessRoute: typeof AuthPendingAccessRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthInvitationRoute: AuthInvitationRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPendingAccessRoute: AuthPendingAccessRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedOrganizationIdSettingsIntegrationsRouteRouteChildren {
  ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute: typeof ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute
  ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute: typeof ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute
}

const ProtectedOrganizationIdSettingsIntegrationsRouteRouteChildren: ProtectedOrganizationIdSettingsIntegrationsRouteRouteChildren =
  {
    ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute:
      ProtectedOrganizationIdSettingsIntegrationsApiKeysRoute,
    ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute:
      ProtectedOrganizationIdSettingsIntegrationsWebhooksRoute,
  }

const ProtectedOrganizationIdSettingsIntegrationsRouteRouteWithChildren =
  ProtectedOrganizationIdSettingsIntegrationsRouteRoute._addFileChildren(
    ProtectedOrganizationIdSettingsIntegrationsRouteRouteChildren,
  )

interface ProtectedOrganizationIdSettingsRouteRouteChildren {
  ProtectedOrganizationIdSettingsIntegrationsRouteRoute: typeof ProtectedOrganizationIdSettingsIntegrationsRouteRouteWithChildren
  ProtectedOrganizationIdSettingsBillingRoute: typeof ProtectedOrganizationIdSettingsBillingRoute
  ProtectedOrganizationIdSettingsBrandingRoute: typeof ProtectedOrganizationIdSettingsBrandingRoute
  ProtectedOrganizationIdSettingsDangerRoute: typeof ProtectedOrganizationIdSettingsDangerRoute
  ProtectedOrganizationIdSettingsDocumentsRoute: typeof ProtectedOrganizationIdSettingsDocumentsRoute
  ProtectedOrganizationIdSettingsGeneralRoute: typeof ProtectedOrganizationIdSettingsGeneralRoute
  ProtectedOrganizationIdSettingsIndexRoute: typeof ProtectedOrganizationIdSettingsIndexRoute
}

const ProtectedOrganizationIdSettingsRouteRouteChildren: ProtectedOrganizationIdSettingsRouteRouteChildren =
  {
    ProtectedOrganizationIdSettingsIntegrationsRouteRoute:
      ProtectedOrganizationIdSettingsIntegrationsRouteRouteWithChildren,
    ProtectedOrganizationIdSettingsBillingRoute:
      ProtectedOrganizationIdSettingsBillingRoute,
    ProtectedOrganizationIdSettingsBrandingRoute:
      ProtectedOrganizationIdSettingsBrandingRoute,
    ProtectedOrganizationIdSettingsDangerRoute:
      ProtectedOrganizationIdSettingsDangerRoute,
    ProtectedOrganizationIdSettingsDocumentsRoute:
      ProtectedOrganizationIdSettingsDocumentsRoute,
    ProtectedOrganizationIdSettingsGeneralRoute:
      ProtectedOrganizationIdSettingsGeneralRoute,
    ProtectedOrganizationIdSettingsIndexRoute:
      ProtectedOrganizationIdSettingsIndexRoute,
  }

const ProtectedOrganizationIdSettingsRouteRouteWithChildren =
  ProtectedOrganizationIdSettingsRouteRoute._addFileChildren(
    ProtectedOrganizationIdSettingsRouteRouteChildren,
  )

interface ProtectedOrganizationIdRouteRouteChildren {
  ProtectedOrganizationIdSettingsRouteRoute: typeof ProtectedOrganizationIdSettingsRouteRouteWithChildren
  ProtectedOrganizationIdIndexRoute: typeof ProtectedOrganizationIdIndexRoute
  ProtectedOrganizationIdEnvelopesNewRoute: typeof ProtectedOrganizationIdEnvelopesNewRoute
  ProtectedOrganizationIdTemplatesTemplateIdRoute: typeof ProtectedOrganizationIdTemplatesTemplateIdRoute
  ProtectedOrganizationIdArchiveIndexRoute: typeof ProtectedOrganizationIdArchiveIndexRoute
  ProtectedOrganizationIdEnvelopesIndexRoute: typeof ProtectedOrganizationIdEnvelopesIndexRoute
  ProtectedOrganizationIdNotificationsIndexRoute: typeof ProtectedOrganizationIdNotificationsIndexRoute
  ProtectedOrganizationIdPeopleIndexRoute: typeof ProtectedOrganizationIdPeopleIndexRoute
  ProtectedOrganizationIdTemplatesIndexRoute: typeof ProtectedOrganizationIdTemplatesIndexRoute
  ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute: typeof ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute
  ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute: typeof ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute
}

const ProtectedOrganizationIdRouteRouteChildren: ProtectedOrganizationIdRouteRouteChildren =
  {
    ProtectedOrganizationIdSettingsRouteRoute:
      ProtectedOrganizationIdSettingsRouteRouteWithChildren,
    ProtectedOrganizationIdIndexRoute: ProtectedOrganizationIdIndexRoute,
    ProtectedOrganizationIdEnvelopesNewRoute:
      ProtectedOrganizationIdEnvelopesNewRoute,
    ProtectedOrganizationIdTemplatesTemplateIdRoute:
      ProtectedOrganizationIdTemplatesTemplateIdRoute,
    ProtectedOrganizationIdArchiveIndexRoute:
      ProtectedOrganizationIdArchiveIndexRoute,
    ProtectedOrganizationIdEnvelopesIndexRoute:
      ProtectedOrganizationIdEnvelopesIndexRoute,
    ProtectedOrganizationIdNotificationsIndexRoute:
      ProtectedOrganizationIdNotificationsIndexRoute,
    ProtectedOrganizationIdPeopleIndexRoute:
      ProtectedOrganizationIdPeopleIndexRoute,
    ProtectedOrganizationIdTemplatesIndexRoute:
      ProtectedOrganizationIdTemplatesIndexRoute,
    ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute:
      ProtectedOrganizationIdEnvelopesEnvelopeIdEditRoute,
    ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute:
      ProtectedOrganizationIdEnvelopesEnvelopeIdIndexRoute,
  }

const ProtectedOrganizationIdRouteRouteWithChildren =
  ProtectedOrganizationIdRouteRoute._addFileChildren(
    ProtectedOrganizationIdRouteRouteChildren,
  )

interface ProtectedMeRouteRouteChildren {
  ProtectedMeDocumentsNewRoute: typeof ProtectedMeDocumentsNewRoute
  ProtectedMeDocumentsIndexRoute: typeof ProtectedMeDocumentsIndexRoute
  ProtectedMeDocumentsEnvelopeIdEditRoute: typeof ProtectedMeDocumentsEnvelopeIdEditRoute
  ProtectedMeDocumentsEnvelopeIdIndexRoute: typeof ProtectedMeDocumentsEnvelopeIdIndexRoute
}

const ProtectedMeRouteRouteChildren: ProtectedMeRouteRouteChildren = {
  ProtectedMeDocumentsNewRoute: ProtectedMeDocumentsNewRoute,
  ProtectedMeDocumentsIndexRoute: ProtectedMeDocumentsIndexRoute,
  ProtectedMeDocumentsEnvelopeIdEditRoute:
    ProtectedMeDocumentsEnvelopeIdEditRoute,
  ProtectedMeDocumentsEnvelopeIdIndexRoute:
    ProtectedMeDocumentsEnvelopeIdIndexRoute,
}

const ProtectedMeRouteRouteWithChildren =
  ProtectedMeRouteRoute._addFileChildren(ProtectedMeRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedOrganizationIdRouteRoute: typeof ProtectedOrganizationIdRouteRouteWithChildren
  ProtectedMeRouteRoute: typeof ProtectedMeRouteRouteWithChildren
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOrganizationIdRouteRoute:
    ProtectedOrganizationIdRouteRouteWithChildren,
  ProtectedMeRouteRoute: ProtectedMeRouteRouteWithChildren,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicVerifyRoute: typeof PublicVerifyRoute
  PublicSignAccessTokenRoute: typeof PublicSignAccessTokenRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicVerifyRoute: PublicVerifyRoute,
  PublicSignAccessTokenRoute: PublicSignAccessTokenRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface EmbedRouteRouteChildren {
  EmbedSignAccessTokenRoute: typeof EmbedSignAccessTokenRoute
}

const EmbedRouteRouteChildren: EmbedRouteRouteChildren = {
  EmbedSignAccessTokenRoute: EmbedSignAccessTokenRoute,
}

const EmbedRouteRouteWithChildren = EmbedRouteRoute._addFileChildren(
  EmbedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  EmbedRouteRoute: EmbedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
