#!/usr/bin/env node

/**
 * Centralized Environment Variable Distribution Script
 *
 * Usage: node scripts/env-apply.js [dev|stag|prod]
 *
 * Reads from .env.[dev|stag|prod] at project root and distributes variables
 * to their respective destinations based on section headers.
 *
 * Sections:
 *   [VITE]               -> apps/web/.env
 *   [SUPABASE_CONFIG]    -> supabase/.env
 *   [SUPABASE_FUNCTIONS] -> supabase/functions/.env
 *   [MCP]                -> .env (PM scripts: Plane, Outline)
 */

const fs = require("fs");
const path = require("path");

const SECTION_DESTINATIONS = {
    VITE: "frontend/vite",
    SUPABASE_CONFIG: "frontend/vite/supabase",
    SUPABASE_FUNCTIONS: "frontend/vite/supabase/functions",
    MCP: ".",
};

function parseArgs() {
    const args = process.argv.slice(2);
    let env = null;

    for (const arg of args) {
        if (["dev", "stag", "prod"].includes(arg.toLowerCase())) {
            env = arg.toLowerCase();
            break;
        }
    }

    if (!env) {
        console.error("Usage: node scripts/env-apply.js [dev|stag|prod]");
        console.error("  dev  = development (local Supabase)");
        console.error("  stag = staging");
        console.error("  prod = production");
        process.exit(1);
    }

    return env;
}

function parseEnvFile(content) {
    const lines = content.split("\n");
    const shared = {};
    const sections = {};

    let currentSection = "SHARED";
    sections[currentSection] = [];

    for (const line of lines) {
        const trimmed = line.trim();

        const sectionMatch = trimmed.match(/^#\s*\[([A-Z_]+)\]/);
        if (sectionMatch) {
            currentSection = sectionMatch[1];
            if (!sections[currentSection]) {
                sections[currentSection] = [];
            }
            continue;
        }

        if (trimmed.startsWith("#") || trimmed === "") continue;

        const eqIndex = trimmed.indexOf("=");
        if (eqIndex > 0) {
            const key = trimmed.substring(0, eqIndex).trim();
            const value = trimmed.substring(eqIndex + 1);

            if (currentSection === "SHARED") {
                shared[key] = value;
            } else {
                sections[currentSection].push({ key, value });
            }
        }
    }

    return { shared, sections };
}

function resolveReferences(value, shared) {
    return value.replace(/\$\{([^}]+)\}/g, (match, varName) => {
        if (shared.hasOwnProperty(varName)) {
            return shared[varName];
        }
        console.warn(`  Warning: Reference \${${varName}} not found in SHARED section`);
        return match;
    });
}

function writeSection(sectionName, variables, shared, projectRoot, envSuffix) {
    const destPath = SECTION_DESTINATIONS[sectionName];
    if (!destPath) {
        console.warn(`  Warning: Unknown section [${sectionName}], skipping`);
        return false;
    }

    const fullPath = path.join(projectRoot, destPath, ".env");
    const dirPath = path.dirname(fullPath);

    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }

    const lines = [
        `# Generated by env-apply.js`,
        `# Source: .env.${envSuffix}`,
        `# Do not edit directly - modify .env.${envSuffix} instead`,
        "",
    ];

    for (const { key, value } of variables) {
        const resolvedValue = resolveReferences(value, shared);
        lines.push(`${key}=${resolvedValue}`);
    }

    fs.writeFileSync(fullPath, lines.join("\n") + "\n");
    console.log(
        `  ✓ ${sectionName} -> ${path.relative(projectRoot, fullPath)} (${variables.length} vars)`
    );
    return true;
}

function main() {
    const env = parseArgs();
    const envNames = { dev: "development", stag: "staging", prod: "production" };

    console.log(`\nApplying ${envNames[env]} environment...\n`);

    const projectRoot = path.resolve(__dirname, "..");
    const sourceFile = path.join(projectRoot, `.env.${env}`);

    if (!fs.existsSync(sourceFile)) {
        console.error(`Error: Source file not found: ${sourceFile}`);
        console.error(`\nCreate .env.${env} at the project root.`);
        console.error("Copy from .env.example and fill in the values.");
        process.exit(1);
    }

    const content = fs.readFileSync(sourceFile, "utf-8");
    const { shared, sections } = parseEnvFile(content);

    const sharedCount = Object.keys(shared).length;
    if (sharedCount > 0) {
        console.log(`Found ${sharedCount} shared variable(s)\n`);
    }

    let sectionsWritten = 0;
    for (const [sectionName, variables] of Object.entries(sections)) {
        if (sectionName === "SHARED" || variables.length === 0) continue;
        if (writeSection(sectionName, variables, shared, projectRoot, env)) {
            sectionsWritten++;
        }
    }

    if (sectionsWritten === 0) {
        console.warn("\nWarning: No sections were written. Check your .env file format.");
        console.warn("Sections should be marked with: # [SECTION_NAME]");
    } else {
        console.log(`\n✓ Applied ${envNames[env]} environment to ${sectionsWritten} location(s)\n`);
    }
}

main();
